# Generated by Django 5.0.6 on 2024-07-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0004_jeudeplateau'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='date_retour',
            field=models.DateField(blank=True, null=True),
        ),
    ]
